### PR TITLE
Modify reduce pipeline to simulate noise and foregrounds without CMB

### PR DESCRIPTION
**Pull request by keskitalo**
To replace the signal with a simulation, add these command line options:
```
    --skymodel_sim skymodel_cache/sky_model_857GHz_nside2048_fwhm10.0.fits \
    --skymodelderiv_sim skymodel_cache/sky_model_deriv_857GHz_nside2048_fwhm10.0.fits \
    --MC_start 0 \
    --MC_count 1 \
    --simulate_noise \
    --simulate_signal \
    --freq_sigma 0 \
    --out sim_0000
```

### CODE REVIEW

**Comment by keskitalo** [comment]
@Helbouha have you had a chance to test these modifications?

**Comment by Helbouha** [comment]
@keskitalo My test is failing with the following error: `KeyError: 'Data buffer (nor alias) theta_857-1 does not exist'`, more specifically at this [line](https://github.com/planck-npipe/toast-npipe/blob/sim_without_cmb/toast_planck/reproc_ring.py#L2381)

**Comment by keskitalo** [comment]
I don't quite understand the source of the failure.  I added a critical fix to an unrelated issue. Can you please pull, recompile and run with `--simulate_signal` added to the earlier options.

**Comment by Helbouha** [comment]
I'm getting an `Exception occurred: "Cannot load sky model, no file specified."`, despite specifying `skymodel` in the options. I see in the log file however that `skymodel_sim=None, skymodelderiv_sim=None` could that be the issue?

**Comment by keskitalo** [comment]
My instructions above have a typo in them... Instead of
```
    --skymodel skymodel_cache/sky_model_857GHz_nside2048_fwhm10.0.fits \
    --skymodelderiv skymodel_cache/sky_model_deriv_857GHz_nside2048_fwhm10.0.fits \
```
You need
```
    --skymodel_sim skymodel_cache/sky_model_857GHz_nside2048_fwhm10.0.fits \
    --skymodelderiv_sim skymodel_cache/sky_model_deriv_857GHz_nside2048_fwhm10.0.fits \
```
I have no clue how the error got in there.

**Comment by keskitalo** [comment]
Are we ready to merge this PR?

**Comment by Helbouha** [comment]
Yes! It works fine, no objections on my part!

**Review by Helbouha — APPROVED** [review]

**Pull request merged**
